### ISSUE TITLE
Cannot install nb_anacondacloud

### ISSUE THREAD

**Issue by ijstokes** [Anaconda-Platform/nb_anacondacloud#25]
First time I've had a problem with this.  `nb_anacondacloud` won't install.  Turns out it is an `anaconda-client` version issue, so it looks like the package's dependencies should specify `anaconda-client>=1.4.0`:

```
$ conda update anaconda-client
Using Anaconda Cloud api site https://api.anaconda.org
Fetching package metadata: ......
Solving package specifications: .........

Package plan for installation in environment /Users/ijstokes/anaconda/envs/trialbox:

The following packages will be UPDATED:

    anaconda-client: 1.2.1-py27_0 --> 1.4.0-py27_0
```

That solved the problem, but the issue I had you can see in the trace below.

```
$ conda install -y -c anaconda-nb-ext
ensions nb_anacondacloud nb_conda nb_conda_kernels
Using Anaconda Cloud api site https://api.anaconda.org
Fetching package metadata: ........
Solving package specifications: .........

Package plan for installation in environment /Users/ijstokes/anaconda/envs/trialbox:

The following NEW packages will be INSTALLED:

    nb_anacondacloud: 1.0.0-py27_0
    nb_conda:         1.0.0-py27_0
    nb_conda_kernels: 1.0.0-py27_0

Linking packages ...
Traceback (most recent call last):
  File "/Users/ijstokes/anaconda/envs/trialbox/bin/jupyter-nbextension", line 6, in <module>
    sys.exit(notebook.nbextensions.main())
  File "/Users/ijstokes/anaconda/envs/trialbox/lib/python2.7/site-packages/jupyter_core/application.py", line 267, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/Users/ijstokes/anaconda/envs/trialbox/lib/python2.7/site-packages/traitlets/config/application.py", line 592, in launch_instance
    app.start()
  File "/Users/ijstokes/anaconda/envs/trialbox/lib/python2.7/site-packages/notebook/nbextensions.py", line 952, in start
    super(NBExtensionApp, self).start()
  File "/Users/ijstokes/anaconda/envs/trialbox/lib/python2.7/site-packages/jupyter_core/application.py", line 256, in start
    self.subapp.start()
  File "/Users/ijstokes/anaconda/envs/trialbox/lib/python2.7/site-packages/notebook/nbextensions.py", line 860, in start
    self.toggle_nbextension_python(self.extra_args[0])
  File "/Users/ijstokes/anaconda/envs/trialbox/lib/python2.7/site-packages/notebook/nbextensions.py", line 836, in toggle_nbextension_python
    logger=self.log)
  File "/Users/ijstokes/anaconda/envs/trialbox/lib/python2.7/site-packages/notebook/nbextensions.py", line 459, in enable_nbextension_python
    logger=logger)
  File "/Users/ijstokes/anaconda/envs/trialbox/lib/python2.7/site-packages/notebook/nbextensions.py", line 374, in _set_nbextension_state_python
    m, nbexts = _get_nbextension_metadata(module)
  File "/Users/ijstokes/anaconda/envs/trialbox/lib/python2.7/site-packages/notebook/nbextensions.py", line 1114, in _get_nbextension_metadata
    m = import_item(module)
  File "/Users/ijstokes/anaconda/envs/trialbox/lib/python2.7/site-packages/traitlets/utils/importstring.py", line 39, in import_item
    return __import__(parts[0])
  File "/Users/ijstokes/anaconda/envs/trialbox/lib/python2.7/site-packages/nb_anacondacloud/__init__.py", line 3, in <module>
    from .handlers import load_jupyter_server_extension
  File "/Users/ijstokes/anaconda/envs/trialbox/lib/python2.7/site-packages/nb_anacondacloud/handlers.py", line 12, in <module>
    from .uploader import Uploader, AccountManager
  File "/Users/ijstokes/anaconda/envs/trialbox/lib/python2.7/site-packages/nb_anacondacloud/uploader.py", line 10, in <module>
    from binstar_client.utils import get_server_api, store_token
ImportError: cannot import name get_server_api
Traceback (most recent call last):
  File "/Users/ijstokes/anaconda/envs/trialbox/bin/jupyter-serverextension", line 6, in <module>
    sys.exit(notebook.serverextensions.main())
  File "/Users/ijstokes/anaconda/envs/trialbox/lib/python2.7/site-packages/jupyter_core/application.py", line 267, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/Users/ijstokes/anaconda/envs/trialbox/lib/python2.7/site-packages/traitlets/config/application.py", line 592, in launch_instance
    app.start()
  File "/Users/ijstokes/anaconda/envs/trialbox/lib/python2.7/site-packages/notebook/serverextensions.py", line 301, in start
    super(ServerExtensionApp, self).start()
  File "/Users/ijstokes/anaconda/envs/trialbox/lib/python2.7/site-packages/jupyter_core/application.py", line 256, in start
    self.subapp.start()
  File "/Users/ijstokes/anaconda/envs/trialbox/lib/python2.7/site-packages/notebook/serverextensions.py", line 218, in start
    self.toggle_server_extension_python(arg)
  File "/Users/ijstokes/anaconda/envs/trialbox/lib/python2.7/site-packages/notebook/serverextensions.py", line 207, in toggle_server_extension_python
    m, server_exts = _get_server_extension_metadata(package)
  File "/Users/ijstokes/anaconda/envs/trialbox/lib/python2.7/site-packages/notebook/serverextensions.py", line 335, in _get_server_extension_metadata
    m = import_item(module)
  File "/Users/ijstokes/anaconda/envs/trialbox/lib/python2.7/site-packages/traitlets/utils/importstring.py", line 39, in import_item
    return __import__(parts[0])
  File "/Users/ijstokes/anaconda/envs/trialbox/lib/python2.7/site-packages/nb_anacondacloud/__init__.py", line 3, in <module>
    from .handlers import load_jupyter_server_extension
  File "/Users/ijstokes/anaconda/envs/trialbox/lib/python2.7/site-packages/nb_anacondacloud/handlers.py", line 12, in <module>
    from .uploader import Uploader, AccountManager
  File "/Users/ijstokes/anaconda/envs/trialbox/lib/python2.7/site-packages/nb_anacondacloud/uploader.py", line 10, in <module>
    from binstar_client.utils import get_server_api, store_token
ImportError: cannot import name get_server_api
Error: Error: post-link failed for: nb_anacondacloud-1.0.0-py27_0                                  |   0%
```

Conda details:

```
$ conda list
# packages in environment at /Users/ijstokes/anaconda/envs/trialbox:
#
_license                  1.1                      py27_1    defaults
abstract-rendering        0.5.1               np110py27_0    defaults
alabaster                 0.7.6                    py27_0    defaults
anaconda-client           1.2.1                    py27_0    defaults
anaconda                  custom                   py27_0    defaults
appnope                   0.1.0                    py27_0    defaults
appscript                 1.0.1                    py27_0    <unknown>
argcomplete               1.0.0                    py27_1    defaults
astropy                   1.0.6               np110py27_0    defaults
babel                     2.1.1                    py27_0    defaults
backports-abc             0.4                       <pip>
backports.shutil-which    3.5.1                     <pip>
backports.shutil_which    3.5.1           py27_1_ga3f1bd9    anaconda-nb-extensions
backports.ssl-match-hostname 3.4.0.2                   <pip>
backports_abc             0.4                      py27_0    defaults
beautifulsoup4            4.4.1                    py27_0    ioos
bitarray                  0.8.1                    py27_0    <unknown>
blaze                     0.8.3                     <pip>
blaze-core                0.8.3                    py27_0    defaults
bokeh                     0.10.0                   py27_0    defaults
boto                      2.38.0                   py27_0    defaults
bottleneck                1.0.0               np110py27_0    defaults
cdecimal                  2.3                      py27_0    defaults
cffi                      1.2.1                    py27_0    defaults
chest                     0.2.3                    py27_0    defaults
cloudpickle               0.2.1                    py27_0    defaults
clyent                    1.2.0                    py27_0    defaults
colorama                  0.3.3                    py27_0    <unknown>
configobj                 5.0.6                    py27_0    defaults
cryptography              1.0.2                    py27_0    defaults
curl                      7.45.0                        0    defaults
cycler                    0.9.0                    py27_0    conda-forge
cython                    0.23.4                   py27_1    defaults
cytoolz                   0.7.4                    py27_0    defaults
dask                      0.8.2                    py27_0    defaults
datashape                 0.4.7               np110py27_1    defaults
decorator                 4.0.4                    py27_0    defaults
docutils                  0.12                     py27_0    <unknown>
dynd                      9b63882                   <pip>
dynd-python               0.7.0                    py27_0    defaults
enum34                    1.0.4                    py27_0    <unknown>
fastcache                 1.0.2                    py27_0    <unknown>
flask                     0.10.1                   py27_1    <unknown>
freetype                  2.5.5                         0    defaults
funcsigs                  0.4                      py27_0    <unknown>
futures                   3.0.5                    py27_0    defaults
gevent                    1.0.1                    py27_0    <unknown>
gevent-websocket          0.9.3                    py27_0    <unknown>
graphviz                  0.4.10                    <pip>
greenlet                  0.4.9                    py27_0    defaults
grin                      1.2.1                    py27_1    <unknown>
h5py                      2.5.0               np110py27_4    defaults
hdf5                      1.8.15.1                      2    defaults
heapdict                  1.0.0                    py27_0    defaults
idna                      2.0                      py27_0    defaults
ipaddress                 1.0.14                   py27_0    defaults
ipykernel                 4.1.1                    py27_0    defaults
ipython                   4.0.1                    py27_0    defaults
ipython-genutils          0.1.0                     <pip>
ipython-notebook          4.0.4                    py27_0    defaults
ipython-qtconsole         4.0.1                    py27_0    defaults
ipython_genutils          0.1.0                    py27_0    defaults
ipywidgets                4.1.0                    py27_0    defaults
itsdangerous              0.24                     py27_0    defaults
jbig                      2.1                           0    defaults
jdcal                     1.0                      py27_0    defaults
jedi                      0.9.0                    py27_0    https://conda.binstar.org/asmeurer/osx-64/jedi-0.9.0-py27_0.tar.bz2
jinja2                    2.8                      py27_0    defaults
jpeg                      8d                            1    <unknown>
jsonschema                2.4.0                    py27_0    <unknown>
jupyter                   1.0.0                    py27_2    defaults
jupyter-client            4.1.1                     <pip>
jupyter-console           4.0.3                     <pip>
jupyter-core              4.0.6                     <pip>
jupyter_client            4.1.1                    py27_0    defaults
jupyter_console           4.0.3                    py27_0    defaults
jupyter_core              4.0.6                    py27_0    defaults
launcher                  1.0.0                         3    defaults
libdynd                   0.7.0                         0    defaults
libgd                     2.1.1                         0    defaults
libpng                    1.6.17                        0    defaults
libtiff                   4.0.6                         1    defaults
libwebp                   0.5.0                         0    defaults
libxml2                   2.9.2                         0    defaults
libxslt                   1.1.28                        2    <unknown>
llvmlite                  0.8.0                    py27_0    defaults
locket                    0.2.0                    py27_0    defaults
lxml                      3.4.4                    py27_0    defaults
markupsafe                0.23                     py27_0    <unknown>
matplotlib                1.5.0               np110py27_0    defaults
mistune                   0.7.1                    py27_0    defaults
multipledispatch          0.4.8                    py27_0    defaults
nb-anacondacloud          1.0.0                     <pip>
nb-conda                  1.0.0                     <pip>
nb-conda-kernels          1.0.0                     <pip>
nb-config-manager         0.1.3                     <pip>
nb-delta                  0.3.1                     <pip>
nb_conda                  1.0.0                    py27_0    anaconda-nb-extensions
nb_conda_kernels          1.0.0                    py27_0    anaconda-nb-extensions
nb_config_manager         0.1.3                    py27_0    anaconda-nb-extensions
nb_delta                  0.3.1                    py27_0    anaconda-nb-extensions
nbconvert                 4.0.0                    py27_0    defaults
nbdime                    0.1.0                    py27_3    anaconda-nb-extensions
nbformat                  4.0.1                    py27_0    defaults
nbpresent                 3.0.0                    py27_0    anaconda-nb-extensions
nbsetuptools              0.1.5                    py27_0    anaconda-nb-extensions
networkx                  1.10                     py27_0    defaults
nltk                      3.1                      py27_0    defaults
node-webkit               0.10.1                        0    <unknown>
nose                      1.3.7                    py27_0    defaults
notebook                  4.2.0                    py27_0    defaults
numba                     0.22.1              np110py27_0    defaults
numexpr                   2.4.4               np110py27_0    defaults
numpy                     1.10.1                   py27_0    defaults
odo                       0.3.4                    py27_0    defaults
openpyxl                  2.2.6                    py27_0    defaults
openssl                   1.0.2d                        0    defaults
pandas                    0.17.1              np110py27_0    defaults
partd                     0.3.2                    py27_1    defaults
path.py                   8.1.2                    py27_1    defaults
patsy                     0.4.0               np110py27_0    defaults
pep8                      1.6.2                    py27_0    defaults
pexpect                   3.3                      py27_0    defaults
pickleshare               0.5                      py27_0    defaults
pillow                    3.0.0                    py27_1    defaults
pip                       8.1.1                    py27_1    defaults
ply                       3.8                      py27_0    defaults
psutil                    3.3.0                    py27_0    defaults
ptyprocess                0.5                      py27_0    defaults
py                        1.4.30                   py27_0    defaults
pyasn1                    0.1.9                    py27_0    defaults
pyaudio                   0.2.7                    py27_0    defaults
pycosat                   0.6.1                    py27_0    defaults
pycparser                 2.14                     py27_0    defaults
pycrypto                  2.6.1                    py27_0    <unknown>
pycurl                    7.19.5.1                 py27_3    defaults
pyflakes                  1.0.0                    py27_0    defaults
pygments                  2.0.2                    py27_0    <unknown>
pyopenssl                 0.15.1                   py27_1    defaults
pyparsing                 2.0.3                    py27_0    defaults
pyqt                      4.11.4                   py27_1    defaults
pytables                  3.2.2               np110py27_0    defaults
pytest                    2.8.1                    py27_0    defaults
python                    2.7.11                        0    defaults
python-dateutil           2.4.2                    py27_0    defaults
python.app                1.2                      py27_4    defaults
pytz                      2015.7                   py27_0    defaults
pyyaml                    3.11                     py27_1    defaults
pyzmq                     14.7.0                   py27_1    defaults
qt                        4.8.7                         1    defaults
qtconsole                 4.1.1                    py27_0    defaults
readline                  6.2                           2    <unknown>
redis                     2.6.9                         0    <unknown>
redis-py                  2.10.3                   py27_0    <unknown>
requests                  2.8.1                    py27_0    defaults
rope                      0.9.4                    py27_1    <unknown>
scikit-image              0.11.3              np110py27_0    defaults
scikit-learn              0.17                np110py27_1    defaults
scipy                     0.16.0              np110py27_1    defaults
setuptools                18.5                     py27_0    defaults
simplegeneric             0.8.1                    py27_0    defaults
singledispatch            3.4.0.3                  py27_0    numba
sip                       4.16.9                   py27_0    defaults
six                       1.10.0                   py27_0    defaults
snowballstemmer           1.2.0                    py27_0    defaults
sockjs-tornado            1.0.1                    py27_0    <unknown>
sphinx                    1.3.1                    py27_0    defaults
sphinx-rtd-theme          0.1.7                     <pip>
sphinx_rtd_theme          0.1.7                    py27_0    defaults
spyder                    2.3.8                    py27_0    defaults
spyder-app                2.3.8                    py27_0    defaults
sqlalchemy                1.0.9                    py27_0    defaults
sqlite                    3.8.4.1                       1    <unknown>
ssl_match_hostname        3.4.0.2                  py27_0    <unknown>
statsmodels               0.6.1               np110py27_0    defaults
sympy                     0.7.6.1                  py27_0    defaults
tables                    3.2.2                     <pip>
terminado                 0.5                      py27_1    defaults
tk                        8.5.18                        0    <unknown>
toolz                     0.7.4                    py27_0    defaults
tornado                   4.3                      py27_0    defaults
traitlets                 4.0.0                    py27_0    defaults
ujson                     1.33                     py27_0    defaults
unicodecsv                0.14.1                   py27_0    defaults
werkzeug                  0.11.2                   py27_0    defaults
wheel                     0.26.0                   py27_1    defaults
xlrd                      0.9.4                    py27_0    defaults
xlsxwriter                0.7.7                    py27_0    defaults
xlwings                   0.5.0                    py27_0    defaults
xlwt                      1.0.0                    py27_0    defaults
xz                        5.0.5                         0    defaults
yaml                      0.1.6                         0    defaults
zeromq                    4.1.3                         0    defaults
zlib                      1.2.8                         0    <unknown>
```

**Comment by damianavila** [comment]
This is probably stale by now... we are now in nb_ancondaclould 1.4.0 and anaconda-client 1.6.3. Let's close it for now and re-open if somebody else reproduce it.
